apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: application-secrets
  namespace: slacathon26
spec:
  path: secret/ad/ad-accel-online-ml-default/slacathon26/secret
  type: Opaque
  keys:
    - SLACATHON_ALTCHA_HMAC_KEY
    - SLACATHON_PUBLIC_URL
    - SLACATHON_SMTP_HOST
    - SLACATHON_SMTP_FROM
