apiVersion: v1
kind: Service
metadata:
  name: slacathon26
  namespace: slacathon26
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: slacathon26
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
